### ISSUE TITLE
Eureka Level parsing incorrect (and bozja stuff)

### ISSUE THREAD

**Issue by robotbrain** [xivapi/lodestone-parser#10]
On characters with both eureka and bozja levels,
- the eureka level object is mangled (max is a string instead of a number)
- the eureka level object returns the character's bozja leveling info
https://cdn.discordapp.com/attachments/731879112196620319/766303374835449907/unknown.png

**Comment by viion** [comment]
Should be fixed in https://github.com/xivapi/lodestone-parser/releases/tag/2.0.1

**Comment by viion** [comment]
Deployed fix live. There is a new entry: `ClassJobsBozjan`

Could you test to see if things are working as expected now.

**Comment by robotbrain** [comment]
Works perfectly on my end, tysm
