### ISSUE TITLE
Isn't returning character specific totals

### ISSUE THREAD

**Issue by snazzyj** [xivapi/lodestone-parser#7]
https://github.com/xivapi/lodestone-parser/blob/658918a0e930dba812fade530086b19ebff1c95a/src/Lodestone/Parser/ParseCharacterMounts.php#L23

trying to get character-specific totals, however it's just returning the total amount of mounts/minions with empty arrays

![Screen_Shot_2019-09-08_at_2 47 36_PM](https://user-images.githubusercontent.com/48457459/64649961-a32a3500-d3e3-11e9-8d11-9c87678a0cd9.png)

**Comment by viion** [comment]
Hello,

This parse logic is for the mobile view not the desktop view, are you definitely getting empty arrays?
